### ISSUE TITLE
KWIC output changed? docname variable now uses "text1", "text2", instead of filnames

### ISSUE THREAD

**Issue by hannann** [kbenoit/quanteda#1020]
(First post, apologies if the question is not written clearly enough)
Hello, 
Until recently, kwic searches outputted a data frame with a docname variable which used the  filename from the texts originally read in (e.g. "party_date"). However, currently, KWIC searches output "text1", "text2", as the docnames instead. The files in the folder from which I am importing are formatted as "party_date.txt" 

I have noticed that this is not the case for kwic's run on "data_corpus_inaugural", so the problem may just be something I'm doing, though I am using the same same data and commands I was using previously. 
I'd be happy for a way to set the variable names when creating a kwic, but from reading previous posts I gather that is not an option. 

Any thoughts? 
Thank you, 
Hanan

**Comment by kbenoit** [comment]
The row names of the output data.frame from `kwic()` are the names of the character vector if the input is type `character`. If these are not named, then the default document stem is applied, which is “text”. You can change this using `quanteda_options()`. This does not happen with the built-in corpus objects because these have document names.

**Comment by hannann** [comment]
Thank you for your quick reply!
Hanan
