### ISSUE TITLE
How to exclude nested collocations?

### ISSUE THREAD

**Issue by koheiw** [kbenoit/quanteda#1050]
`textstat_collocations` extract 'united states congress' and 'states congress' from the inaugural corpus.
```r
require(quanteda)
require(stringi)

toks <- tokens(data_corpus_inaugural)
toks <- tokens_remove(toks, stopwords(), padding = TRUE)
col_cap <- textstat_collocations(tokens_keep(toks, '^[A-Z]', 'regex', FALSE, padding = TRUE), size = 2:3)
col_cap[stri_detect_fixed(col_cap$collocation, 'congress'),]

#               collocation count length    lambda         z
# 61        states congress     2      2  2.209743  3.446450
# 63 united states congress     2      3 -2.152404 -1.014623
```
But 'states congress' only appears as part of 'united states congress', so it is redundant.
```r
kwic(toks, phrase('states congress'))                                                                                          
# [2005-Bush, 23:24] , Members United | States Congress | , reverend clergy, distinguished
# [2013-Obama, 14:15] , Members United | States Congress | , distinguished guests, 
```
Nested collocations are ignored in `tokens_compound()`, but they make interpreting collocation analysis results difficult. It is good to have an option to ignore nested collocations in `textstat_collocations` itself.

**Comment by kbenoit** [comment]
Since all collocation scoring is done separately for each value of `size`, this function literally scores each ngram separately - the use of vectors here is just for convenience.

Our emerging recommendation will be to score longest ones first, compound those, and then try to form shorter ones, but this relies on using the p-values as a threshold to decide compounding, and is beyond the scope `textstat_collocations()`. So the basic answer is: User Beware.

**Comment by koheiw** [comment]
I came up with a great idea.
