### ISSUE TITLE
reproducible error when creating a document-frequent matrix

### ISSUE THREAD

**Issue by haodong** [kbenoit/quanteda#114]
Hi, I'm studying nlp and processing a large corpus.
I cut it into pieces to create dfm with fixed parameter.
The things is weird is that it report error every time in 5th segment.
Here are my info:

```R
> sessionInfo()
R version 3.2.4 Revised (2016-03-16 r70336)
Platform: x86_64-apple-darwin15.3.0 (64-bit)
Running under: OS X 10.11.3 (El Capitan)

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] gmatrix_0.3      data.table_1.9.6 quanteda_0.9.5-5 vimcom_1.2-7    

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.3        lattice_0.20-33    mvtnorm_1.0-5      SnowballC_0.5.1    chron_2.3-47      
 [6] grid_3.2.4         stringi_1.0-1      ca_0.64            Matrix_1.2-4       boot_1.3-18       
[11] tools_3.2.4        foreign_0.8-66     parallel_3.2.4     rsconnect_0.4.1.11 manipulate_1.0.1  
[16] DescTools_0.99.16 
> 

...
Processing... 1 , left... 366 ,current size is 48 bytes 
Creating a dfm from a corpus ...
   ... lowercasing
   ... tokenizing
   ... indexing documents: 11,634 documents
   ... indexing features: 229,034 feature types
   ... stemming features (English), trimmed 19018 feature variants
   ... created a 11634 x 210016 sparse dfm
   ... complete. 
Elapsed time: 26.874 seconds.
   ... merging matrices ...   
   ...  1.597404e-05  ...   
Processing... 2 , left... 365 ,current size is 14.3 Mb 
Creating a dfm from a corpus ...
   ... lowercasing
   ... tokenizing
   ... indexing documents: 11,634 documents
   ... indexing features: 232,091 feature types
   ... stemming features (English), trimmed 19452 feature variants
   ... created a 11634 x 212639 sparse dfm
   ... complete. 
Elapsed time: 28.644 seconds.
   ... merging matrices ...   
   ...  0.07804513  ...   
Processing... 3 , left... 364 ,current size is 24.6 Mb 
Creating a dfm from a corpus ...
   ... lowercasing
   ... tokenizing
   ... indexing documents: 11,634 documents
   ... indexing features: 227,685 feature types
   ... stemming features (English), trimmed 18914 feature variants
   ... created a 11634 x 208771 sparse dfm
   ... complete. 
Elapsed time: 27.975 seconds.
   ... merging matrices ...   
   ...  0.110889  ...   
Processing... 4 , left... 363 ,current size is 33.4 Mb 
Creating a dfm from a corpus ...
   ... lowercasing
   ... tokenizing
   ... indexing documents: 11,634 documents
   ... indexing features: 229,987 feature types
   ... stemming features (English), trimmed 19338 feature variants
   ... created a 11634 x 210649 sparse dfm
   ... complete. 
Elapsed time: 29.981 seconds.
   ... merging matrices ...   
   ...  0.13434  ...   
Processing... 5 , left... 362 ,current size is 41.6 Mb 
Creating a dfm from a corpus ...
   ... lowercasing
   ... tokenizing
   ... indexing documents: 11,634 documents
   ... indexing features: 228,819 feature types
   ... stemming features (English)
 Hide Traceback
 
 Rerun with Debug
 Error in validObject(r) : 
  invalid class “dgTMatrix” object: length(Dimnames[1]) differs from Dim[1] which is 11633 
12 stop(msg, ": ", errors, domain = NA) 
11 validObject(r) 
10 sparseMatrix(i = x@i + 1, j = newFeatureIndex, x = x@x, dimnames = list(docs = docnames(x), 
    features = newFeatures)) 
9 wordstem.dfm(dfmresult, language) 
8 wordstem(dfmresult, language) 
7 dfm.tokenizedTexts(tokenizedTexts, verbose = verbose, toLower = toLower, 
    stem = stem, ignoredFeatures = ignoredFeatures, keptFeatures = keptFeatures, 
    language = language, thesaurus = thesaurus, dictionary = dictionary, 
    valuetype = valuetype, startTime = startTime) 
6 dfm(tokenizedTexts, verbose = verbose, toLower = toLower, stem = stem, 
    ignoredFeatures = ignoredFeatures, keptFeatures = keptFeatures, 
    language = language, thesaurus = thesaurus, dictionary = dictionary, 
    valuetype = valuetype, startTime = startTime) 
5 dfm.character(texts, verbose = verbose, ...) 
4 dfm(texts, verbose = verbose, ...) 
3 dfm.corpus(tmp, stem = TRUE, ngrams = n, toLower = TRUE, removeNumbers = TRUE, 
    removeSeparators = TRUE, removePunct = TRUE, removeTwitter = TRUE, 
    removeHyphens = TRUE, language = "english") 
2 dfm(tmp, stem = TRUE, ngrams = n, toLower = TRUE, removeNumbers = TRUE, 
    removeSeparators = TRUE, removePunct = TRUE, removeTwitter = TRUE, 
    removeHyphens = TRUE, language = "english") 
1 segmWF(txt = cTxt, n = 2) 
```

btw, the time for stemming is too slow. Is there any method to speed it up like using parallel (I noticed that package "parllel" is mentioned in your description but nothing more) or gpu computing ([this one](https://github.com/bkase/CUDA-grep))?

**Comment by kbenoit** [comment]
What happens if you try to process just the fifth dfm?

I'm not sure what is happening in your loop, and don't have access to your data, so this is a long way from being reproducible, but I'll try to help as much as I can.

Ken

Sent from my iPad so there could be strange auto-corruptions

On 20 Mar 2016, at 10:36, Hao Dong <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi, I'm studying nlp and processing a large corpus.
I cut it into pieces to create dfm with fixed parameter.
The things is weird is that it report error every time in 5th segment.
Here are my info:

> sessionInfo()
R version 3.2.4 Revised (2016-03-16 r70336)
Platform: x86_64-apple-darwin15.3.0 (64-bit)
Running under: OS X 10.11.3 (El Capitan)

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

other attached packages:
[1] gmatrix_0.3      data.table_1.9.6 quanteda_0.9.5-5 vimcom_1.2-7

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.3        lattice_0.20-33    mvtnorm_1.0-5      SnowballC_0.5.1    chron_2.3-47
 [6] grid_3.2.4         stringi_1.0-1      ca_0.64            Matrix_1.2-4       boot_1.3-18
[11] tools_3.2.4        foreign_0.8-66     parallel_3.2.4     rsconnect_0.4.1.11 manipulate_1.0.1
[16] DescTools_0.99.16
>

...
Processing... 1 , left... 366 ,current size is 48 bytes
Creating a dfm from a corpus ...
   ... lowercasing
   ... tokenizing
   ... indexing documents: 11,634 documents
   ... indexing features: 229,034 feature types
   ... stemming features (English), trimmed 19018 feature variants
   ... created a 11634 x 210016 sparse dfm
   ... complete.
Elapsed time: 26.874 seconds.
   ... merging matrices ...
   ...  1.597404e-05  ...
Processing... 2 , left... 365 ,current size is 14.3 Mb
Creating a dfm from a corpus ...
   ... lowercasing
   ... tokenizing
   ... indexing documents: 11,634 documents
   ... indexing features: 232,091 feature types
   ... stemming features (English), trimmed 19452 feature variants
   ... created a 11634 x 212639 sparse dfm
   ... complete.
Elapsed time: 28.644 seconds.
   ... merging matrices ...
   ...  0.07804513  ...
Processing... 3 , left... 364 ,current size is 24.6 Mb
Creating a dfm from a corpus ...
   ... lowercasing
   ... tokenizing
   ... indexing documents: 11,634 documents
   ... indexing features: 227,685 feature types
   ... stemming features (English), trimmed 18914 feature variants
   ... created a 11634 x 208771 sparse dfm
   ... complete.
Elapsed time: 27.975 seconds.
   ... merging matrices ...
   ...  0.110889  ...
Processing... 4 , left... 363 ,current size is 33.4 Mb
Creating a dfm from a corpus ...
   ... lowercasing
   ... tokenizing
   ... indexing documents: 11,634 documents
   ... indexing features: 229,987 feature types
   ... stemming features (English), trimmed 19338 feature variants
   ... created a 11634 x 210649 sparse dfm
   ... complete.
Elapsed time: 29.981 seconds.
   ... merging matrices ...
   ...  0.13434  ...
Processing... 5 , left... 362 ,current size is 41.6 Mb
Creating a dfm from a corpus ...
   ... lowercasing
   ... tokenizing
   ... indexing documents: 11,634 documents
   ... indexing features: 228,819 feature types
   ... stemming features (English)
 Hide Traceback

 Rerun with Debug
 Error in validObject(r) :
  invalid class “dgTMatrix” object: length(Dimnames[1]) differs from Dim[1] which is 11633
12 stop(msg, ": ", errors, domain = NA)
11 validObject(r)
10 sparseMatrix(i = x@i + 1, j = newFeatureIndex, x = x@x, dimnames = list(docs = docnames(x),
    features = newFeatures))
9 wordstem.dfm(dfmresult, language)
8 wordstem(dfmresult, language)
7 dfm.tokenizedTexts(tokenizedTexts, verbose = verbose, toLower = toLower,
    stem = stem, ignoredFeatures = ignoredFeatures, keptFeatures = keptFeatures,
    language = language, thesaurus = thesaurus, dictionary = dictionary,
    valuetype = valuetype, startTime = startTime)
6 dfm(tokenizedTexts, verbose = verbose, toLower = toLower, stem = stem,
    ignoredFeatures = ignoredFeatures, keptFeatures = keptFeatures,
    language = language, thesaurus = thesaurus, dictionary = dictionary,
    valuetype = valuetype, startTime = startTime)
5 dfm.character(texts, verbose = verbose, ...)
4 dfm(texts, verbose = verbose, ...)
3 dfm.corpus(tmp, stem = TRUE, ngrams = n, toLower = TRUE, removeNumbers = TRUE,
    removeSeparators = TRUE, removePunct = TRUE, removeTwitter = TRUE,
    removeHyphens = TRUE, language = "english")
2 dfm(tmp, stem = TRUE, ngrams = n, toLower = TRUE, removeNumbers = TRUE,
    removeSeparators = TRUE, removePunct = TRUE, removeTwitter = TRUE,
    removeHyphens = TRUE, language = "english")
1 segmWF(txt = cTxt, n = 2)

btw, the time for stemming is too slow. Is there any method to fasten it like parallel or gpu computing?

**Comment by haodong** [comment]
Hi, @kbenoit .

What I mean by "reproducible" is that this error would occur repeatedly. And the corpus are free to download from web.

Also, this error only appears when I set the parameter of size of cutting pieces to around 1e4. In size=1e5, however, everything goes fine.

As you can see, I use `for` loop to automatically **"dtm"** it with the fixed size.
```R
indexing documents: 11,634 documents
```
In 5th loop, after stemming, the size becomes 11633 according to the error traceback.

```R
 Error in validObject(r) : 
  invalid class “dgTMatrix” object: length(Dimnames[1]) differs from Dim[1] which is 11633 
```

I'll upload my code to github later. Just plz wait.


Best,
Hao

**Comment by haodong** [comment]
Hi kbenoit,

I believe that I've misused some quanteda functions. This error should not appear again. :)


Thanks,
Hao
