### ISSUE TITLE
textfile('tweets.json') is very picky about the format of the JSON file

### ISSUE THREAD

**Issue by adamobeng** [kbenoit/quanteda#167]
This is because streamR::parseTweets expects particular whitespace in the JSON file. For example, [this](https://gist.github.com/adamobeng/405d9c7829f1fecb041edfde0b3bc078) pretty-printed JSON file is not parsed by streamR. cc @pablobarbera 

@kbenoit, should we either
- Fix this upstream
- stop using streamR, and treat Twitter JSON files like any other JSON file (with the small proviso that we extract the "statuses" element from the full API output)?

bugfix branch: [bugfix_tweetjson_dispatch](https://github.com/kbenoit/quanteda/tree/dev_textfile_tests)

**Comment by pablobarbera** [comment]
streamR works with the two standard types of Twitter data in JSON as returned by the API (search data and streaming data). I'm hesitant to modify streamR::parseTweets to deal with this case because precisely the way it identifies from the Streaming API is precisely because it's a new line. I would also say this is a very rare case. I've worked with Twitter data in many formats and I have never had this issue before.

But perhaps there's a better way to fix this that I'm not seeing -- feel free to send a pull request to the streamR repo as well! :-)

PS. Also note that this particular example is from search data, which is not the most common. Tweets from the Streaming API just come line by line, and there's no way to parse the entire file in JSON, you also need to parse it line by line.

**Comment by adamobeng** [comment]
Good to see you, @pablobarbera!

The approach I would suggest is this:

1. Try to load the whole file as one JSON object
    - if there is a 'search_metadata' field in the object, iterate over the 'statuses' field
    - if the object is actually a list, iterate over the list (this would happen for output from `statuses/{mentions,user,home}_timeline.json`, etc.)
2. If that fails, run through the file line-by-line, trying to treat each line as a JSON-serialised Tweet

This doesn't cover the case where there are multiple pretty-printed JSON objects in a file (i.e. with internal newlines) — but even I agree that case is pathological.

Would you accept a patch that did that?
