### ISSUE TITLE
Thanks

### ISSUE THREAD

**Issue by bthomas-ds** [kbenoit/quanteda#216]
I really struggled on using other NLP libraries. The other packages threw multicore errors and memory errors. Imagine, 24 gb and 4 cores and still getting errors. Quanteda rock 'n rocked right through the text in seconds.

**Comment by kbenoit** [comment]
Delighted to hear that, thanks for the feedback! Any impressions you have, or feature requests, are welcome so that we can improve the software. The idea behind quanteda is to make power accessible to the power user, but also to make it straightforward enough for beginners to find it easy to use as well.
