### ISSUE TITLE
There is no vignette for textfile()

### ISSUE THREAD

**Issue by adamobeng** [kbenoit/quanteda#217]
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/9231340245136/156067377006772)

**Comment by conjugateprior** [comment]
FYI There are no vignettes at all if you install from github.  A manual `devtools` after building call to construct them wil also drop them in `inst` and fix that.

**Comment by adamobeng** [comment]
Thanks @conjugateprior. Is there a preferable/best practices way of distributing vignettes with github-installed packages?

**Comment by conjugateprior** [comment]
Sure. Build as usual then run `devtools::build_vignettes()`.  That both builds and moves them to `inst`, where installs look for them (they don't seem to look in the `vignettes` directory).

**Comment by adamobeng** [comment]
Thanks.

@kbenoit : Do you want to add this to the process?

**Comment by kbenoit** [comment]
Does this do anything different for the way vignettes appear in CRAN? It should not, right, since CRAN builds just copy the `vignettes` folder (and everything else in `inst/`) to the root. 

I have Studio's option checked to rebuild vignettes with doing Build & Reload so it always calls `devtools::build_vignettes()`. @adamobeng is using some old school neck-bearded vi setup + Terminal solution so he might be skipping this stage :-).
