### ISSUE TITLE
Input the LIWC Error

### ISSUE THREAD

**Issue by dwy904** [kbenoit/quanteda#238]
I was trying to input the liwc dictionary into R

library(quanteda)
mfdict <- dictionary(file = "/Users/WeiyeDeng/Desktop/liwcdic2007.dic", format = "LIWC")

However, the console shows:

Error in readLIWCdict(file, toLower = toLower, encoding = encoding) : 
  Expected a guide (a category legend) delimited by percentage symbols at start of file, none found
In addition: Warning message:
In max(grep("^%\\s*$", d)) :
  no non-missing arguments to max; returning -Inf

Could you teach me how I can fix it ?

**Comment by kbenoit** [comment]
what version are you using? from `packageVersion("quanteda")?

Also you could [email me](mailto:kbenoit@lse.ac.uk) the .dic file and I will check its format.

**Comment by dwy904** [comment]
Here's the information you might need:

> packageVersion("quanteda")
[1] ‘0.9.7.17’

Thank you so much for helping me.

Best,
Michael

**Comment by kbenoit** [comment]
Should still work, so could be something in your file format. Can you email me the file at kbenoit@lse.ac.uk?

**Comment by dwy904** [comment]
sent

**Comment by kbenoit** [comment]
Thanks, I looked at it. It's not a correctly formatted LIWC dictionary file, because there is no category header. See the description for correctly formatted LIWC dictionary files [here](https://www.google.co.uk/url?sa=t&rct=j&q=&esrc=s&source=web&cd=3&cad=rja&uact=8&ved=0ahUKEwi9sPv03eDNAhXEVxoKHcU3D54QFggxMAI&url=https%3A%2F%2Fs3-us-west-2.amazonaws.com%2Fdownloads.liwc.net%2FLIWC2015_OperatorManual.pdf&usg=AFQjCNEN2mal2nVHSaUiDNYPicN4uv5j_g&sig2=72rLCkzfZ0VV9v0gTeZSQA), and/or look at the examples in `?dictionary` including the link to the Moral Foundations dictionary.

**Comment by dwy904** [comment]
Is that mean I will no long  be able to implement my LIWC dictionary into
my R analysis ?

Best,
Mike

**Comment by kbenoit** [comment]
It means you can only use properly formatted LIWC dictionaries. The file you are trying to use is not, and therefore would not work with quanteda or even the LIWC software. It refers to categories by number but the header of the file does not have the table of categories.

**Comment by celanal** [comment]
@kbenoit Can I save a LIWC dictionary in any text program and just use the ending .dic?

**Comment by kbenoit** [comment]
Yes. You don't even need to use the ending `.dic` if you specify `'format = "liwc"`.
