### ISSUE TITLE
Can you explain?

### ISSUE THREAD

**Issue by cownr10r** [kbenoit/quanteda#273]
Dear Dr. Benoit,

Can you explain the numbers underneath the "topics" under the "https://cran.r-project.org/web/packages/quanteda/vignettes/quickstart.html#topic-models" page? are these to be the numbers of highest term frequencies? I appreciate your help. Thanks very much.

<img width="892" alt="screen shot 2016-11-04 at 7 22 36 pm" src="https://cloud.githubusercontent.com/assets/7209507/20026386/fe9e56f0-a2c7-11e6-9cef-8cbca8ab2309.png">

**Comment by kbenoit** [comment]
Those results are from the `topics()` and `terms()` functions from the **topicmodels** package and not something that is part of **quanteda**. Briefly, however, those are the counts of terms or topics (depending on which function you called) for each document, in actual counts. (Other packages, such as **lda**, tend to return proportions instead of counts.) 

To understand these better, I suggest the topicmodels tag on [StackOverflow](http://stackoverflow.com/questions/tagged/topicmodels).

**Comment by cownr10r** [comment]
Tks, Dr. Benoit. I have figured it out on my own. As always, thanks for your code. :-)
