### ISSUE TITLE
Too many lapply in tokens generator

### ISSUE THREAD

**Issue by koheiw** [kbenoit/quanteda#287]
R's lapply function is slow compared to R's vectorized operations or C++ loops. But we are using many lapply in the tokens generator. One solution is to use C++ function for simple cleaning like ``result <- qatd_cpp_remove_string_list(result, "")`` (I used this already and tokenization became 30% faster). 

If the operation is not so simple, we can put lapply together. For example,
```
result <- lapply(result, function(x){ 
      x <- stringi::stri_replace_all_charclass(x, "[\\p{S}]", "")
      x[which(x != "")]
})
```
instead of 
```
result <- lapply(result, stringi::stri_replace_all_charclass, "[\\p{S}]", "")
result <- lapply(result, function(x) x <- x[which(x != "")])
```
This is basically why our tokenizer is slower than ``tokenizers``.

**Comment by kbenoit** [comment]
I've asked @amatsuo to do a complete review of how we tokenise, and compare this to the **tokenizers** package, since I would like to make the tokenization modular. I am thinking we would have 

*  tokenisers approach (using our existing default of **stringi**)  
*  split on `"\\s"` (currently: `tokenize(x, what = "fasterword")`)  
*  split on `" "` (currently: `tokenize(x, what = "fastest")`)  
*  use a parser, e.g. the under-development **spacyr** package  

How about we postpone tokeniser performance issues until we have a handle on these?

**Comment by koheiw** [comment]
This is just a note for @amatsuo. Use a profiler to find bottlenecks like,
```
library(profvis)
profvis(
  tokens(txt, what='fastestword')
)
```  
This profiler is so useful, so that it was integrated into R lately.

**Comment by kbenoit** [comment]
@koheiw are we happy with this now?

**Comment by koheiw** [comment]
I changed the way lapply is used when I added the incremental tokenizer. We can close this issue.
