### ISSUE TITLE
topfeatures per-document option

### ISSUE THREAD

**Issue by adamobeng** [kbenoit/quanteda#336]

**Comment by koheiw** [comment]
It is easy to implement this, but how it should look like?
```r
topfeatures(mx)
```
or
```r
apply(mx, 1, topfeatures)
```

**Comment by stefan-mueller** [comment]
Good idea! I'd prefer the first option as the structure seems to be more similar to the general **quanteda** syntax.

**Comment by kbenoit** [comment]
Output would be a sorted list, much like:

```r
sink("/dev/null"); example(textstat_simil); sink()
head(as.list(s1), 2)
# $`1993-Clinton`
# 1997-Clinton   2009-Obama   2013-Obama    2001-Bush    2005-Bush   2017-Trump 
#    0.6660288    0.6288108    0.6278986    0.5333062    0.5092769    0.5033731 
# 
# $`1997-Clinton`
#   2009-Obama   2013-Obama 1993-Clinton    2001-Bush   2017-Trump    2005-Bush 
#    0.6954614    0.6826705    0.6660288    0.6434983    0.6136180    0.5535663 
```
Possibilities for syntax:
1. For real consistency, we deprecate `topfeatures()` and provide a `textstat_frequency()` function. 
2. Use the `by_document = TRUE` as @koheiw suggests
3. Use `by = docnames(x)` as a default, but allow this to be a grouping variable, including docvar names.

Could of course combine 1 and (2 or 3).

Not pressing on the groups since since we already have a `dfm_group()`, and the `by_document` option would give the same result if `dfm_group()` were run first.
