### ISSUE TITLE
Reduce sizes of corpus objects using memCompress

### ISSUE THREAD

**Issue by koheiw** [kbenoit/quanteda#360]
We can achieve 70% reduction only by doing this. Why not?
```
> txt <- readLines('/home/kohei/Documents/Brexit/Analysis/all_bbc_2015.txt')
> object.size(txt)
85996936 bytes
> txt_comp <- memCompress(txt, 'gzip')
> object.size(txt_comp)
28275136 bytes
> txt2 <- unlist(strsplit(memDecompress(txt_comp, 'gzip', asChar = TRUE), "\n"), use.names = FALSE)
> object.size(txt2)
85996936 bytes
> identical(txt, txt2)
[1] TRUE
```

**Comment by kbenoit** [comment]
Is this as simple as being able to `memCompress` the data.frame inside a corpus object, and `memDecompress` it on access? What are the performance implications? Given that a corpus object is only accessed infrequently, they might not matter.

Would be worth prototyping with `kwic` and `texts` (including with `group = ""`). 

Suggestions on how to try:

1.  Create a new constructor function called `corpusgzip` that constructs a `corpusgzip` object where the `documents` data.frame inside it is compressed. This should have a class tag of `corpusgzip` added to the `corpus` tag, so that 
    ```r
    class(x) <- c("corpusgzip", "corpus", "list")
    ```

2. Rewrite `texts`, `texts<-`, `docvars`, and `docvars<-` and compare performance.

    Most of the functions below will work automatically with the new object if you rewrite those, since they all access the `corpus` object internals through those four functions. (or should, anyway...)
    ```r
    > methods(class = "corpus")
     [1] [                    [[                   [[<-                 +                    as.character        
     [6] c                    coerce               collocations         dfm                  docnames            
    [11] docvars              docvars<-            initialize           kwic                 metacorpus          
    [16] metadoc              ndoc                 nsentence            ntoken               ntype               
    [21] phrasetotoken        print                sample               segment              settings            
    [26] show                 slotsFromS3          subset               summary              texts               
    [31] texts<-              textstat_readability tokenize             tokens               toLower             
    [36] toUpper    
    ```         

3.  If we are happy with it, we fold the compression handling into the core constructor `corpus()` and get rid of `corpusgzip`.

    And that will REALLY stop people from trying to pry open a corpus object and bypassing the accessor functions!

**Comment by koheiw** [comment]
Sounds like a plan. It will also encourage people like me to use the corpus object.

**Comment by kbenoit** [comment]
It would be nice to generalise the storage mechanism for the core table in a `corpus` object, since it would give us options for future use such as data.table, filehash, or SQLite. 

If we are careful to access those internals only through our own accessor and replacement functions, then most of the methods for corpus objects will work seamlessly once we add corpus variant methods for the core accessor and replacement functions.

At the moment I think these are just `texts`, `texts<-`, `docvars`, and `docvars<-`.

**Comment by koheiw** [comment]
memCompress only accepts raw or character vectors, so texts should be in a separate vector from the data frame. I think this structure is good for the generalization.
```
> df <- data.frame(text=txt)
> df_comp <- memCompress(df)
Error in memCompress(df) : 'from' must be raw or character
> df <- data.frame(text=txt_comp, var=rep(1, length(txt)))
Error in data.frame(text = txt_comp, var = rep(1, length(txt))) : 
  arguments imply differing number of rows: 28275095, 26184
```

**Comment by koheiw** [comment]
It takes 5 seconds to compress or decompress 85MB character vector.
```
Unit: seconds
       expr      min       lq     mean   median       uq      max neval
   compress 4.562650 4.590090 4.694828 4.637580 4.683804 5.231013    10
 decompress 4.696923 4.764873 4.801810 4.810518 4.852090 4.917426    10
```

**Comment by kbenoit** [comment]
Have you looked at the [**bigmemory** package](https://cran.r-project.org/web/packages/bigmemory/vignettes/Overview.pdf)?

**Comment by koheiw** [comment]
irlba package for SVD uses this packaged as an option, but it stopped working once I installed bigmemory . So I do not trust it much. Generally, I am very careful about using functions in other packages. I like memCompress because it is in R base.

**Comment by kbenoit** [comment]
```r
> data_corpuszip_guardian <- corpus(texts(data_corpus_guardian), docvars = docvars(data_corpus_guardian), compress = TRUE)
> system.time(toks <- tokens(data_corpus_guardian))
   user  system elapsed 
 87.119   2.390  89.627 
> system.time(toks <- tokens(data_corpuszip_guardian))
   user  system elapsed 
126.572   3.448 130.176 
```
so it's about 40 seconds to decompress in memory, on my machine at least!
