### ISSUE TITLE
Review C++ code, add tests, prune defunct functions

### ISSUE THREAD

**Issue by kbenoit** [kbenoit/quanteda#431]
Includes:  
*  adding documentation where needed  
*  adding tests where needed, esp for exported functions, but also for non-exported (non-R) functions if this is possible - I am not sure it's possible using `testthat`  
*  overall review  
*  make some notes about a map of which C++ functions are called by which core R functions

**Comment by koheiw** [comment]
Me and Haiyan have different styles in C++ code. I am saying that my style is the best, but mixing camel and snake type is not good. Following, `stringi`'s style, I think we should use snake types in exported functions.

I have attached the `_mt` suffix to many of the C++ file names, but it is no longer necessary because serial and parallel version are the same file using macro. Please just rename the files.

**Comment by kbenoit** [comment]
> I am saying that my style is the best

Is this a https://www.youtube.com/watch?v=PaZ0ad8dFEg sort of thing?

🤣 🥋

**Comment by kbenoit** [comment]
snake_case is preferred: https://github.com/kbenoit/quanteda/wiki/Style-guide

**Comment by HaiyanLW** [comment]
https://whathecode.wordpress.com/2011/02/10/camelcase-vs-underscores-scientific-showdown/

**Comment by koheiw** [comment]
There was a type: 'I do NOT mean that my style is the best...`. You understood : )
