### ISSUE TITLE
Add min_len to dfm_trim()

### ISSUE THREAD

**Issue by koheiw** [kbenoit/quanteda#443]
We can remove short features from `dfm` by `dfm_remove(mx, '^.{1,2}$', valuetype='regex')` but it is more convenient to use `min_len` argument.

**Comment by kbenoit** [comment]
I agree this is a good feature but it's not very consistent with `dfm_trim`, whose description is:

> trim a dfm using frequency threshold-based feature selection

Trimming on characteristics of the featname is not frequency-based.

Is this not easy enough?

```r
> (dfm1 <- dfm(data_corpus_inaugural))
Document-feature matrix of: 57 documents, 9,174 features (91.6% sparse).
> dfm1[, nchar(featnames(dfm1)) >= 4]
Document-feature matrix of: 57 documents, 8,938 features (92.2% sparse).
```

**Comment by koheiw** [comment]
I can live with your approach until we find a proper place for the function.

**Comment by kbenoit** [comment]
A natural place for it would be in `dfm_select`, which selects features. The new argument could be called `min_nchar = 1`, and should probably also include a `max_nchar = NULL` (where the values are defaults, and `NULL` means no maximum, or alternatively we could let NULL mean no maximum but set the limit to something reasonable such as 63.

[Because:](http://theweek.com/articles/463500/8-favorite-ridiculously-long-german-words)
```r
> stringi::stri_length("rindfleischetikettierungsüberwachungsaufgabenübertragungsgesetz")
[1] 63
```
😆

**Comment by koheiw** [comment]
Sounds like a good idea.

**Comment by kbenoit** [comment]
I'll code it now as a break from the boredom of editorial duties.

**Comment by kbenoit** [comment]
@koheiw See the code in `dfm_select`. Suggests we should add a similar set of arguments and approach to `tokens_select`.
