### ISSUE TITLE
clean(x) returns as "character" when x has class "corpus"

### ISSUE THREAD

**Issue by chrishanretty** [kbenoit/quanteda#45]
The documentation states that 

> "If x is a corpus, ‘clean’ returns the corpus containing the cleaned texts". 

But 

`class(clean(inaugCorpus))` gives `character`, instead of `corpus`.

**Comment by kbenoit** [comment]
Yes that needs to be corrected in the documentation.  Please see the Design “vignette” in the dev branch for a statement of our planned principles.  We want to make a corpus’s set of texts “immutable” meaning that you can only modify them after extraction.  The only exception will be encoding conversion, which we are working on.

We are also phasing out clean - the new tokenize() and toLower() in our workngDev branch, soon to become dev branch, implement the cleaning according to the design document in a much better (and much faster!) way.


On 15 Jun 2015, at 17:37, chrishanretty <notifications@github.com<mailto:notifications@github.com>> wrote:


The documentation states that

"If x is a corpus, ‘clean’ returns the corpus containing the cleaned texts".

But

class(clean(inaugCorpus)) gives character, instead of corpus.

**Comment by pnulty** [comment]
Well, I just changed the behaviour to match the documentation. As long as clean.corpus exists, then I think it makes sense that it should return a corpus. However, as Ken says, this will change in the next version.

**Comment by kbenoit** [comment]
Final resolution of this: We have removed `clean()` altogether. The new cleaning functions are housed inside `tokenize()`. If you want to transform to lowercase, use `toLower()`.
