### ISSUE TITLE
dictionary() recognizes "NA" as N/A

### ISSUE THREAD

**Issue by koheiw** [kbenoit/quanteda#458]
I am making a hierarchical geographical dictionary, whose keys include a country code NA for Namibia. `dictionary()` recognize the key as N/A and raises an error.
 ```
AFR
	SOUTH
		BW
			Botswana (1)
			Botswanan* (1)
			Gaborone (1)
		LS
			Lesotho (1)
			Lesothonian* (1)
			Maseru (1)
		NA
			Namibia (1)
			Namibian* (1)
			Windhoek (1)
		ZA
			South Africa (1)
			S African (1)
			SA (1)
			South African* (1)
			S African* (1)
			Cape Town (1)
			Johannesburg (1)
		SZ
			Swaziland (1)
			Swazi* (1)
			Lobamba (1)
			Mbabane (1)
```
Also, how can I chose a level from in `tokens_lookup` or `dfm_lookup`? We need a option for this.

**Comment by kbenoit** [comment]
Solved in https://github.com/kbenoit/quanteda/commit/4f8f99b88a9916f088889168fce7f5a6bf91b039 - see the test I added.

This is not entirely satisfactory however, since it does not read the hierarchically flattened names correctly (see the test in the above commit). This may be an issue with an "improperly" formatted `.cat` dictionary file, but this would still indicate a big lack of robustness.

Note that to enter this as a list, you would need to quote the `NA`:

```r
dictionary(list(AFR = list(SOUTH = list("NA" = c("Namibia", "Namibian*", "Windhoek"), LS = "Lesotho"))))
# Dictionary object with 2 key entries.
#  - AFR.SOUTH.NA: Namibia, Namibian*, Windhoek
#  - AFR.SOUTH.LS: Lesotho
```
