### ISSUE TITLE
toLower and tolower are  confusing

### ISSUE THREAD

**Issue by koheiw** [kbenoit/quanteda#478]
There are two lower-casing functions: one from base, `quanteda::toLower()` from `base::tolower()`. The function should be `quanteda::tolower()`, because quanteda's new APIs are snake cased. It is more user friendly to hide `base::tolower()`.

```r
toks <- tokens(data_corpus_inaugural)
length(toks) # 57
nrow(dfm(toks, tolower=FALSE))  # 57
length(toLower(toks)) # 57
length(tolower(toks)) # 148045
```

**Comment by kbenoit** [comment]
Agreed, we need to remove the remaining camelCase arguments from functions. `tokens()` still has these, but they have not been changed (yet) because argument name changes are much harder to deprecate than function name changes.

currently however the older `toLower()` has been changed to more specific functions, such as:
* `dfm_tolower()`
* `tokens_tolower()`
* `dfm_tolower`
* `char_tolower` (a wrapper around `stringi::stri_trans_tolower()` with an added `keep_acronyms` argument)

But we still have the argument `toLower` in:
* `collocations()`
* the functions to read dictionaries, in `dictionaries.R`
* `summary.corpus()` and `summary.character()`

It's possible to trap what shows up in `...` and issue a warning, e.g.
```r
> dfm("A C C C C C", toLower = FALSE)
Document-feature matrix of: 1 document, 2 features (0% sparse).
1 x 2 sparse Matrix of class "dfmSparse"
       features
docs    a c
  text1 1 5
Warning message:
In tokens.character(x, ...) : Argument toLower not used.
```
or even to examine `...` for the deprecated arguments and issue a specific warning about their deprecation.

**Comment by koheiw** [comment]
OK. I will use `tokens_tolower()` and `dfm_tolower()`.

**Comment by kbenoit** [comment]
Done for function names, but needs to be added for function arguments. We can deprecate them as an argument like this:

```r
ellipsis_args <- list(...)
if (!is.null(ellipsis_args$toLower)) {
    warning("argument \"toLower\" is deprecated: use \"tolower\" instead.")
    if (missing(tolower)) tolower <- toLower
}
```
