### ISSUE TITLE
Index Error  for wordshoal

### ISSUE THREAD

**Issue by methodds** [kbenoit/quanteda#488]
After finding single row groups / authors thanks to #481 , using ``textmodel_wordshoal`` raises another error:
```
shoal14 <- textmodel_wordshoal(dfm14, groups = d14p$topic_id, 
                        authors =  d14p$person_id )

Scaling 818 document groups1 2 3 4 5 6 [...] 311


Error in intI(i, n = x@Dim[1], dn[[1]], give.dn = FALSE) : index larger than maximal 10
14.
stop(gettextf("index larger than maximal %d", n), domain = NA)
13.
intI(i, n = x@Dim[1], dn[[1]], give.dn = FALSE)
12.
subCsp_rows(x, i, drop = drop)
11.
as(x, "Matrix")[i, , ..., drop = FALSE]
10.
as(x, "Matrix")[i, , ..., drop = FALSE]
9.
data[zeroLengthDocs, ]
8.
data[zeroLengthDocs, ]
7.
docnames(data[zeroLengthDocs, ])
6.
paste(..., sep = sep)
5.
message(paste(..., sep = sep), appendLF = appendLF)
4.
catm("Note: removed the following zero-token documents:", docnames(data[zeroLengthDocs, ]), "\n")
3.
textmodel_wordfish(groupdfm, dir = dir, tol = c(tol, 1e-08))
2.
textmodel_wordshoal.dfm(dfm14, groups = d14p$topic_id, authors = d14p$person_id)
1.
textmodel_wordshoal(dfm14, groups = d14p$topic_id, authors = d14p$person_id)

```
A  reproduction file is available  [here](https://www.dropbox.com/s/8md9duc7bwoyqs5/WordshoalError.RData?dl=1).

**Comment by kbenoit** [comment]
That was a bug in `textmodel_wordfish` for reporting about how it removes zero-feature count documents, now fixed.

But: It creates a problem in `textmodel_wordshoal` for your data because one "document" contains only a single feature count:

```r
which(ntoken(dfm14)==1)
# text3885 
#     3885 
```

The problem here is that in iteration 312 of `M` in [line 110 of `textmodel-wordshoal.R`](https://github.com/kbenoit/quanteda/blob/master/R/textmodel-wordshoal.R#L110), this feature is removed before sending to `textmodel_wordfish`. (Note to @lauderdale : this line does not implement what the comment states it does, which refers to document frequency and not term frequency as in the code.)

This results in the removal of the only feature, causing a document with all zero feature counts to be sent to `textmodel_wordfish`, which removes this document in [lines 118-121](https://github.com/kbenoit/quanteda/blob/master/R/textmodel-wordfish.R#L118-L121).  This results in a different length of theta being returned to `textmodel_wordshoal` and causes a bug/warning:

```r
Warning message:
In psi[groups == levels(groups)[j]] <- wfresult@theta :
  number of items to replace is not a multiple of replacement length
```

@lauderdale needs to fix this one.

**Comment by kbenoit** [comment]
But a workaround for you @methodds is to get rid of that uninformative document!

**Comment by methodds** [comment]
Thanks for the hint. Is there an easy way to remove rows in dfm's with, say less than 5 non-zero entries and return the corresponding index? This could be used to remove such uninformative documents and the corresponding metadata in a dataframe/corpus

**Comment by kbenoit** [comment]
`dfm_trim`

**Comment by methodds** [comment]
Sorry to highjack this again, but I don't wont to spam you with 240982340 issues: How can I get the group level estimates out of a fitted wordshoal model? Summary only returns the author specific estimates.

**Comment by kbenoit** [comment]
A question for @lauderdale

**Comment by methodds** [comment]
Similar to that @lauderdale : How can I get the word level estimates out of a fitted wordshoal model?

**Comment by kbenoit** [comment]
@lauderdale I'm removing this as a PR and leaving it as an open issue. If you want to pick up where I started, it's branch `dev_wordshoal`.
