### ISSUE TITLE
Relational operators work with dfm in a strange way

### ISSUE THREAD

**Issue by koheiw** [kbenoit/quanteda#533]
Relational operator seems to work with `dfm`, but not always. Is this a bug?
```r
mydfm <- dfm(c(d1 = "b b b b b b b a a a",
               d2 = "a a a a a a a b b"))

mydfm[,'b'] > 1 # Error
mydfm[,'b'] >= 1 # Error
mydfm[,'b'] > 2 # OK
mydfm[,'b'] >= 2 # Error
mydfm[,'b'] > 3 # OK
mydfm[,'b'] >= 3 # OK

```

**Comment by kbenoit** [comment]
The problem is that at the moment, the rules for converting a dfm to a sparse logical (`"lgCMatrix"`) object are not defined. According to your tests above, it works iff the result object does not contain all TRUE or FALSE entries, otherwise it generates an error.

We could add such rules, but of course it is no longer a dfm, since dfm objects record counts and not logicals - but it should at least work robustly to creating a logical (sparse) matrix. This is actually quite easy to do since you just have to compare the `x` in the `dfmSparse`/`dgCMatrix` and using that, construct the `dglMatrix`.
