### ISSUE TITLE
Error when attempting to subset a dfm

### ISSUE THREAD

**Issue by jhfowler** [kbenoit/quanteda#624]
I cannot subset a dfm by feature on version 0.9.9.24 or 0.9.9.42 of quanteda
I used to be able to subset on earlier versions of quanteda (sorry I do not remember which version)
I have uploaded an example of the problem dfm to my website so the error can be replicated

> library(quanteda)
quanteda version 0.9.9.42
Using 23 of 24 cores for parallel computing

Attaching package: ‘quanteda’

The following object is masked from ‘package:utils’:

    View

> d <- readRDS(gzcon(url("http://fowler.ucsd.edu/dfm_all_2016_01_01_00_onepercent.rds")))
> d[,"trump"]

Error in slot(x_orig, s) : 
  no slot of name "skip" for this object of class "dfmSparse"

> dfm_select(d,features="trump")

Error in slot(x_orig, s) : 
  no slot of name "skip" for this object of class "dfmSparse"

> which(colnames(d)=="trump")

[1] 6426

> d[,6426]

Error in slot(x_orig, s) : 
  no slot of name "skip" for this object of class "dfmSparse"

**Comment by kbenoit** [comment]
I suspect you are having this trouble because you created the dfm with an earlier version of **quanteda**, and now the subset operation is not finding a slot (`@skip`) that is in the S4 class definition of a dfm in the newer versions. (Note to @koheiw we could avoid this by putting all such attributes into a list, that could get copied as a list by operations like `[`, rather than having separately named slots.)

This works fine:

```r
data_dfm_LBGexample[, c("C", "D")]
## Document-feature matrix of: 6 documents, 2 features (83.3% sparse).
## 6 x 2 sparse Matrix of class "dfmSparse"
##     features
## docs  C  D
##   R1 10 22
##   R2  0  0
##   R3  0  0
##   R4  0  0
##   R5  0  0
##   V1  0  0
```

Here's a solution for you: Create a new dfm from the dfm. The easiest way is:

```r
dfm(data_dfm_LBGexample)
## Document-feature matrix of: 6 documents, 37 features (54.1% sparse).
```

That should update the slots.

**Comment by jhfowler** [comment]
thanks!
j
