### ISSUE TITLE
Documentation: Clarify intended distinction between docvars() and metadoc()?

### ISSUE THREAD

**Issue by petereckley** [kbenoit/quanteda#675]
When should users prefer one over the other.
And what is the real practical difference in functionality (other than having different getter / setter functions)?

Apologies if I missed this. I couldn't find guidance on [the Stackoverflow quanteda channel](http://stackoverflow.com/questions/tagged/quanteda) either.

**Comment by kbenoit** [comment]
The idea is that document variables are attributes of the document in the sense of variables you might want to use later to subset the corpus, as predictors in machine learning, etc. Such as: party and year in `data_corpus_inaugural`. Metadoc are additional pieces of document-level that allow you to record some things about the document that you might find useful but probably are not things you ever want to use as substantive information in your analysis. Such as: the source of the document, a URL for the document, notes about how it was cleaned, etc.

**Comment by petereckley** [comment]
Thanks @kbenoit 

I think I understand the intended notional distinction as you outline above. What I'm not so clear on is if/how the functionality and implementation (other than accessor functions) differs? If metadoc are implemented as docvars with a "_" prefix, then presumably there is no performance difference? What is then gained from making the distinction explicit in the code, rather than just having docvars which they user may never use as substantive information in their analysis?

Is the idea that you may want to implement differently in future, with e.g. memory saving or performance gains for metadoc due to their more static nature, and so want to retain the distinction in the interface in anticipation?

**Comment by kbenoit** [comment]
No performance difference. The only real difference is that in `corpus_select()`, you can name the docvars (rather than metadoc vars) using non-standard evaluation, as in the `subset()` function, but this needs to be more explicit for metadoc vars.

So:
```r
> corpus_subset(data_corpus_inaugural, President == "Adams") %>% summary
Corpus consisting of 2 documents.

       Text Types Tokens Sentences Year President   FirstName
 1797-Adams   826   2584        37 1797     Adams        John
 1825-Adams  1004   3154        74 1825     Adams John Quincy

Source:  /home/paul/Dropbox/code/quanteda/* on x86_64 by paul
Created: Fri Sep 12 12:41:17 2014
Notes: 
```

but you would need to specify the full metadoc var if you want to subset on that. But if you think  of metadoc vars as something then you would want to record about a document - say the name of the graduate student who cleaned it! - rather than a variable you'd probably ever want to select on, such as the political party of the speaker who produced the document, then you probably would not need to do this. If you did, just treat it as a docvar. The difference is:

```r
> metadoc(data_corpus_irishbudget2010, "cleanedby") <- 
      rep(c("dick", "jane"), ndoc(data_corpus_irishbudget2010)/2)
> summary(data_corpus_irishbudget2010, showmeta = TRUE)
Corpus consisting of 14 documents.

                                  Text Types Tokens Sentences year debate number      foren     name party _cleanedby
       2010_BUDGET_01_Brian_Lenihan_FF  1949   8733       374 2010 BUDGET     01      Brian  Lenihan    FF       dick
      2010_BUDGET_02_Richard_Bruton_FG  1042   4478       217 2010 BUDGET     02    Richard   Bruton    FG       jane
        2010_BUDGET_03_Joan_Burton_LAB  1621   6429       307 2010 BUDGET     03       Joan   Burton   LAB       dick
       2010_BUDGET_04_Arthur_Morgan_SF  1589   7185       343 2010 BUDGET     04     Arthur   Morgan    SF       jane
         2010_BUDGET_05_Brian_Cowen_FF  1618   6697       250 2010 BUDGET     05      Brian    Cowen    FF       dick
          2010_BUDGET_06_Enda_Kenny_FG  1151   4254       153 2010 BUDGET     06       Enda    Kenny    FG       jane
     2010_BUDGET_07_Kieran_ODonnell_FG   681   2309       133 2010 BUDGET     07     Kieran ODonnell    FG       dick
      2010_BUDGET_08_Eamon_Gilmore_LAB  1183   4217       201 2010 BUDGET     08      Eamon  Gilmore   LAB       jane
    2010_BUDGET_09_Michael_Higgins_LAB   490   1288        44 2010 BUDGET     09    Michael  Higgins   LAB       dick
       2010_BUDGET_10_Ruairi_Quinn_LAB   442   1290        59 2010 BUDGET     10     Ruairi    Quinn   LAB       jane
     2010_BUDGET_11_John_Gormley_Green   404   1036        49 2010 BUDGET     11       John  Gormley Green       dick
       2010_BUDGET_12_Eamon_Ryan_Green   512   1651        90 2010 BUDGET     12      Eamon     Ryan Green       jane
     2010_BUDGET_13_Ciaran_Cuffe_Green   444   1248        45 2010 BUDGET     13     Ciaran    Cuffe Green       dick
 2010_BUDGET_14_Caoimhghin_OCaolain_SF  1188   4094       176 2010 BUDGET     14 Caoimhghin OCaolain    SF       jane

Source:  /home/paul/Dropbox/code/quantedaData/* on x86_64 by paul
Created: Tue Sep 16 15:58:21 2014
Notes:  
> corpus_subset(data_corpus_irishbudget2010, metadoc(data_corpus_irishbudget2010, "cleanedby") == "jane") %>% summary(showmeta = TRUE)
Corpus consisting of 7 documents.

                                  Text Types Tokens Sentences year debate number      foren     name party _cleanedby
      2010_BUDGET_02_Richard_Bruton_FG  1042   4478       217 2010 BUDGET     02    Richard   Bruton    FG       jane
       2010_BUDGET_04_Arthur_Morgan_SF  1589   7185       343 2010 BUDGET     04     Arthur   Morgan    SF       jane
          2010_BUDGET_06_Enda_Kenny_FG  1151   4254       153 2010 BUDGET     06       Enda    Kenny    FG       jane
      2010_BUDGET_08_Eamon_Gilmore_LAB  1183   4217       201 2010 BUDGET     08      Eamon  Gilmore   LAB       jane
       2010_BUDGET_10_Ruairi_Quinn_LAB   442   1290        59 2010 BUDGET     10     Ruairi    Quinn   LAB       jane
       2010_BUDGET_12_Eamon_Ryan_Green   512   1651        90 2010 BUDGET     12      Eamon     Ryan Green       jane
 2010_BUDGET_14_Caoimhghin_OCaolain_SF  1188   4094       176 2010 BUDGET     14 Caoimhghin OCaolain    SF       jane

Source:  /home/paul/Dropbox/code/quantedaData/* on x86_64 by paul
Created: Tue Sep 16 15:58:21 2014
Notes:   
```

**Comment by koheiw** [comment]
I am reviewing `docvars()` in relation to #496. I find current `metadoc()` redundant too, because users can access to meta field using `docvars()` without problems. We should reserve the name space begin with an underscore not for the non-essential administrative purposes but for essential internal purposes such as document id (`_docid`), segment id (`_segid`), original document length (`_doclen`) etc. and block users from changing these values (`texts` in corpus should also be`_texts`).

Ideally, users' document variables and quanteda's internal variables should be in separate objects. Only justification to put different types of variables in one data.frame is that it is easier to subset variables with documents when they are together. `corpuszip` is one step forward in this respect. Based on that function, we can separate `texts` and keep raw data on disk to save memory.

**Comment by koheiw** [comment]
This is related to #496. Here is a list of system level document variables that we need:

- document id (integer)
- segment id (integer)
- document names (character)
- document length (integer)
- document groups (factor, optional)

We can reserve variable names that begin with _ or __ for system variables.

**Comment by kbenoit** [comment]
Should we lump this with #373 and solve it then? (For >1.0)

**Comment by kbenoit** [comment]
I'll close this issue and refer to it in #373 since it originally asked a question, and that's been answered.
