### ISSUE TITLE
How to group  documents in dfm?

### ISSUE THREAD

**Issue by koheiw** [kbenoit/quanteda#720]
I am aware that `dfm` has `groups` argument, but what is the right way to group documents in an existing `dfm`? Applying `dfm` on a dfm seems strange to me. Why not creating something like `dfm_group`?
```r
mx <- dfm(data_corpus_asahi_2016_seg, what = "fastestword")
mx_daily <- dfm(mx, groups = docvars(mx, 'date'), what = "fastestword")
mx_daily
Document-feature matrix of: 365 documents, 84,825 features (94.7% sparse).
```

**Comment by kbenoit** [comment]
Because you're constructing a (new) dfm using no additional functionality not found in the original constructor function. Although...we could make the same argument about `dictionary` (`dfm_lookup()`), `remove` (`dfm_remove()`), `select` (`dfm_select()`), and `stem` (`dfm_stem`). From this perspective, adding a `dfm_group()` function would be consistent.

But groups is unique to `dfm()`, since there is no `corpus_` or `tokens_` equivalent, unlike the other options above.

In #690 I was thinking that we would be more consistent if the `corpus()` and `tokens()` constructors also worked on existing objects of the type they aim to construct.

**Comment by koheiw** [comment]
We can make constructors work on the type they create, but, if we design in this way, we would end up having three Swiss knife functions, putting functionality of all other functions in these. This does not makes users' and developers' lives easier.

Making `dfm_group` is a good idea, but we can also upgrade `dfm_compress` as it has relatively few functions and arguments. We can also create `tokens_group` and `corpus_group`, but they just duplicate what `dfm_group` will do in the later stage.
