### ISSUE TITLE
corpus_reshape: reshape to sentences across documents and preserve docvars

### ISSUE THREAD

**Issue by stefan-mueller** [kbenoit/quanteda#723]
In my text corpus some sentences are divided up into several rows (documents) because the docvars differ. 

Is there a way to reshape the corpus to sentences
- even though the sentences are in different documents, and 
- without losing information about the (sometimes different) `docvars`.

```r
# Example
mycorpus <- corpus(c(textone_1 = "This is a sentence",
                     textone_2 = "which continues here.", 
                     textwo = "Here is the last sentence."), 
                   docvars = data.frame(info=c("A", "B", "C")))

mycorpus_reshape <- corpus_reshape(mycorpus, to = "sentences")

summary(mycorpus_reshape)
```
```
# > summary(mycorpus_reshape)
# Corpus consisting of 3 documents.
# 
# Text            Types  Tokens    Sentences   info
# textone_1.1     4      4         1            A
# textone_2.1     4      4         1            B
# textwo.1        6      6         1            C
```
```r
texts(mycorpus_reshape)
```
```
# textone_1.1                  textone_2.1                     textwo.1 
# "This is a sentence"      "which continues here." "Here is the last sentence." 
```

The first two documents are not combined although they belong to the same sentence.

How it could/should like (combine sentences _and_ preserve information on `docvars`):

```
# > summary(mycorpus_reshape)
# Corpus consisting of 2 documents.
# 
# Text                Types  Tokens    Sentences   info
# textone_1.1_2.1     8      8         1            A, B
# textwo.1            6      6         1            C

texts(mycorpus_reshape)

# textone_1.1_2.1                             textwo.1 
# "This is a sentence which continues here." "Here is the last sentence." 
```
Now the two documents are combined, and the `info` docvar holds information on the different values. Possibly there are more elegant solutions, I'd be happy to read your thoughts on this.

**Comment by koheiw** [comment]
I do not think we have a function for this, but you can still hack:

```r
mycorpus <- corpus(c(textone_1 = "This is a sentence",
                     textone_2 = "which continues here.", 
                     textwo = "Here is the last sentence."), 
                   docvars = data.frame(info=c("A", "B", "C")))


docvars(mycorpus, '_docid') <- c(1, 1, 2)
docvars(mycorpus, '_segid') <- c(1, 2, 1)
docvars(mycorpus, '_document') <- c('textone', 'textone', 'textwo')
mycorpus$settings$units <- 'sentences'
mycorpus2 <- corpus_reshape(mycorpus, 'documents')

texts(mycorpus2)
```

**Comment by kbenoit** [comment]
I'm not a fan of hacks, especially those that access internals of the objects (which are subject to change, as we always warn users). Plus the solution above does not preserve the docvars for the first regrouped document as `"A, B"`, it drops the `"B"`.

The first behaviour is correct, that you are reshaping your corpus of three documents into sentence-level documents, which are not different since each document consists of a single "sentence" (although the first does not end with a sentence delimiter, and the second does not start with a capitalised word).

To reshape this to "documents", you need some grouping variable, and then you can reconstruct the corpus with a grouping document:

```r
texts(corpus(texts(mycorpus, groups = "_document")))
##                                     textone                                      textwo 
## "This is a sentence  which continues here."                "Here is the last sentence." 
```

To get compound docvars, if this is even meaningful, we would need to implement a corpus constructor from corpus objects method (see #690), with a 
```r
corpus.corpus(x, groups = "groupvariable", FUN = aggregation_function)`
```
function that could sum, average, or concatenate the docvars in the different documents.

**Comment by koheiw** [comment]
I wonder why @stefan-mueller got such a corpus in the first place. It is caused by the way texts are loaded, isn't it? In this case, the importer or parser needs a fix. 

Yet, we can make a `corpus_group()` as well as `dfm_group` (#720). This is also related to the discussion on how docvars should be stored (#649).

**Comment by stefan-mueller** [comment]
Thanks for your help and ideas! Indeed, a valid question, @koheiw. I work with the [manifestoR](https://github.com/ManifestoProject/manifestoR) package which uses [quasi-sentences](https://manifesto-project.wzb.eu/information/documents?name=handbook_v4). Each "document" in my corpus is therefore one quasi-sentence with several `docvars`. I need to transform them into natural sentences, but retain the `docvars` of each quasi-sentence (sometimes different parts of a sentence belong to different policy areas). Unfortunately, by default the documents do _not_ contain a grouping variable on the sentence level.

The **manifestoR** team thankfully sent me a long function that is based on the **tm** package, and joins the rows to natural sentences. But the code is rather complicated, requires **openNLP** tagging, and is difficult to change. I am aware that not many researchers face similar problems, but maybe you have an idea of how to solve this problem in **quanteda**. 

Even if we cannot solve my specific problem, I think that `dfm_group()` and `corpus_group()` would be very useful in general. Let me know if/how I can help you with this.

**Comment by koheiw** [comment]
It sounds better to keep the quasi-sentences until creation of `dfm` and aggregate them by `dfm_group`  in the analysis stage. We can add several aggregation options (sum, mean, and user function) to `dfm_group`. This `dfm_group` is also useful for bootstrapping (#648).

**Comment by kbenoit** [comment]
I am starting to warm to the idea of separate `corpus_group()` and `dfm_group()` functions, the latter being possible because the `dfm()` retains docvars now, but also being possible to use a set of external variables whose rows correspond to the documents. We should write out a complete proposal for consideration to see how this would work and how it would affect other functions in the eco-system, before coding it.

On @stefan-mueller's use case, this could probably be solved most easily using a combination of **dplyr** and **reshape2** (or **data.table** if you like a bare metal approach - this is how I would do it, using the `by =` option).  You have a data.frame of quasi-sentences with the quasi-sentence text, a sentence ID (where split sentences will have the same value across multiple, split quasi-sentences), and the CMP code. You want to reunite them by quasi-sentence and record a frequency table of codes for each collapsed unit. For this you need a function to aggregate the CMP codes, which will need to be either `list()` or `c()` or `table()`, since these are categorical, but it's possible to have values in a data.table or data.frame with such object types.

To knit the texts together, you use an aggregation function for the texts by quasi-sentence that pastes them. This is all that [`texts(x, groups = "groupingvar")` is doing anyway](https://github.com/kbenoit/quanteda/blob/master/R/corpus-methods-quanteda.R#L120-L121).

Once you've done that operation, you can construct a new corpus using the resulting collapsed object, through the `corpus.data.frame()` method. Until we do add `corpus_groups()` this is probably your best bet. Let me know if you need any help with the **data.table** or **reshape2** code.

I should be getting SO points for this! :wink:

**Comment by stefan-mueller** [comment]
Sorry! Next time I'll use SO for this (thought it might be a more general issue/improvement suggestion, not only my specific problem). We can close this issue (see #725 for more detailed discussion).
