### ISSUE TITLE
DFM breaking for some texts

### ISSUE THREAD

**Issue by myeomans** [kbenoit/quanteda#79]
Love this package, just discovered it and I'm using it to pipe the LIWC dictionary right into R (rather than calculating manually every time). Would love to use this for all text work going forward but it broke on a new dataset I tested.. The error comes on a line that assigns dimnames to an internal matrix. My data are chat transcripts, and lines that break the dfm function have zero words in the text (e.g. "2003.", "2011.", "2012.", "66", "42.", and so on). It only breaks when I'm using dfm to tabulate LIWC features. 

I wrote my own exception handler but just thought you might want to know...

**Comment by kbenoit** [comment]
I'd suggest trying to construct the dfm without the dictionary first - does that work?

Also please include your code and output. If you want me to diagnose and fix the problem, it would be a good idea to email me to the corpus and dictionary objects (or a link to them, e.g. Dropbox URL) too, then I can definitely fix it. kbenoit@lse.ac.uk

**Comment by myeomans** [comment]
dfm worked without the dictionary fine! The dictionary I'm using is the LIWC2007 .dic file, which I probably shouldn't share publicly. The code wasn't more complicated than 
quanteda::dfm(c("this is fine", "2003.", "this is also fine"), dictionary=LIWCFILE)

I should not that I can't seem to reproduce the error right now (i.e. it works!) but I did get it a lot earlier in the week... Since then, I've done a few things (including updating everything) so if i'm the only person that found this, then no big deal!

**Comment by kbenoit** [comment]
I just fixed the LIWC dictionary handling this weekend so the problem might be solved now with the latest Github version 0.9.1-5.

Sent from my iPad so there could be strange auto-corruptions

On 13 Dec 2015, at 00:48, myeomans <notifications@github.com<mailto:notifications@github.com>> wrote:


dfm worked without the dictionary fine! The dictionary I'm using is the LIWC2007 .dic file, which I probably shouldn't share publicly. The code wasn't more complicated than
quanteda::dfm(c("this is fine", "2003.", "this is also fine"), dictionary=LIWCFILE)

I should not that I can't seem to reproduce the error right now (i.e. it works!) but I did get it a lot earlier in the week... Since then, I've done a few things (including updating everything) so if i'm the only person that found this, then no big deal!

-
