### ISSUE TITLE
textmodel_wordscores: LBG transformation in predict function

### ISSUE THREAD

**Issue by thomasd2** [kbenoit/quanteda#816]
The transformation uses all documents rather than the virgin texts only as in the original paper. Is this intended or a bug?

```
dUK <- data_corpus_ukmanifestos
dUK <- corpus_subset(dUK, Year >= 1992 & Year <= 1997 & 
                       (Party == "Con" | Party == "Lab" | Party == "LD") )

dfmUK <- dfm(tokens(dUK, 
                    remove_punct=TRUE,
                    remove_hyphens=FALSE,
                    remove_numbers=TRUE) )
docnames(dfmUK)

myws <- textmodel_wordscores(dfmUK, c(17.21, 5.35, 8.21, rep(NA, 3)) )

(mywsPredLBG <- predict(myws, rescaling="lbg"))

ts <- mywsPredLBG@textscores[,1]
# the function uses all the texts (including the reference texts)
mean(ts) + (ts-mean(ts))*(sd(myws@y[1:3])/sd(ts))
mywsPredLBG@textscores$textscore_lbg
# replicate procedure as in the paper (using only virgin texts)
mean(ts[4:6]) + (ts[4:6]-mean(ts[4:6]))*(sd(myws@y[1:3])/sd(ts[4:6]))
```

**Comment by kbenoit** [comment]
Not a bug, it interprets all data in `newdata` as "virgin" texts. If you want to restrict that from the training set, you need to specify a restricted document range, e.g. `newdata = dfmUK[4:6, ]`.

See `?coef.textmodel` since this is a better way to access the fitted and predicted coefficients than directly access the S4 slots.

If this satisfies your question, pls close the issue.

**Comment by thomasd2** [comment]
Thanks, got it. Perhaps you want to include the above example in the documentation for textmodel_wordscores and its predict function.
