### ISSUE TITLE
textplot_scale1d throws error after textmodel_wordscores with MV transformation

### ISSUE THREAD

**Issue by thomasd2** [kbenoit/quanteda#817]
Following up on #816, there is an error in the plot function, probably because the MV output lacks an se entry or something.
`textplot_scale1d(mywsPredMV, margin = "documents")`
Also, do I understand it correctly that there is no simple way of plotting the original reference scores and LBG-transformed predictions for the virgin texts into one plot, using this function? (If I run predict on all texts, I get transformed scores for the reference documents).

**Comment by stefan-mueller** [comment]
No, so far it's not possible to show the original reference scores into one plot. How would you prefer to display the reference scores? In an extra facet below or above the predicted scores, or in-between the predicted scores? I think the first option might be preferable, otherwise the plot might get confusing.

To get the first option, we could change `textplot_scale1d` and add an option `plot_refscores = TRUE/FALSE` that changes `facet_grid(as.factor(groups)~,…` to `facet_grid(as.factor(groups)~scores_type,…` to plot both the predicted and reference scores. What do you think?

**Comment by thomasd2** [comment]
Cheers, sounds great.

**Comment by stefan-mueller** [comment]
Ok, I will take care of this and make a PR at some stage this week.

**Comment by stefan-mueller** [comment]
These changes do not allow plotting the reference scores and Wordscores predictions for the virgin texts into one plot, as proposed by @thomasd2. As I mentioned above, this seems a bit difficult as the scores for the reference texts are not stored in `coef()` yet.

**Comment by kbenoit** [comment]
The way to print the scores on one function would be something like:
```r
ws <- textmodel_wordscores(data_dfm_lbgexample, c(seq(-1.5, 1.5, .75), NA))
pred_raw <- predict(ws)
coef_mv <- predict(ws, rescaling = "mv")

myplot <- textplot_scale1d(pred_raw)
```
and then modify `myplot` by adding plots of the positions and SEs from `coef_mv`. I don't think it's worth programming this option into the scaling function.
