### ISSUE TITLE
Whitespace error for stemming when constructing a dfm

### ISSUE THREAD

**Issue by methodds** [kbenoit/quanteda#909]
Hi,
related to the discussion in #882 here is another whitespace problem (reproduction file available [here](https://www.dropbox.com/s/1nqsy1uzqulnlyx/quanteda_wordstem.RData?dl=1) ):

````
df_mat <- dfm(out$meta$post_message, stem = TRUE,
remove_separators = FALSE,  remove_url = TRUE)

Error in char_wordstem.character(featnames(x), language = language) : 
  whitespace detected: you can only stem tokenized texts
````

**Comment by kbenoit** [comment]
Ah I know what caused this - you have tokens that consist of whitespace (because `remove_separators = FALSE`), and our stemmer detects multiple words because we forgot to test the condition where a token that is positive for containing whitespace is not itself ONLY whitespace. I will fix this tomorrow.

Are you sure you want keep the separators?

**Comment by methodds** [comment]
Thanks for fixing this :) I probably won't keep the separators. At the moment I'm just doing some robustness checks inspired by the [preText](https://github.com/matthewjdenny/preText) package.
