### ISSUE TITLE
remove or restore kwic join argument

### ISSUE THREAD

**Issue by kbenoit** [kbenoit/quanteda#916]
I think we agreed to remove this from the signature of `kwic()`, since it's inactive. I thought I'd raise this as an issue before I remove it from the function signature. See also #912.

**Comment by koheiw** [comment]
We cannot remove this until a target words-based collocation finder is implemented (#521). I am keeping it only to create a tokens out of a kwic object.

**Comment by kbenoit** [comment]
Does it do anything in `kwic()` at the moment? Can you show me an example of the difference it causes when the setting is changed?

**Comment by koheiw** [comment]
```r
toks <- tokens("a b c d")

kw1 <- kwic(toks, c('b', 'c'))

colSums(dfm(as.tokens(kw1))) # tokens are double counted

kw2 <- kwic(toks, c('b', 'c'), join = TRUE)

colSums(dfm(as.tokens(kw2)))
```

**Comment by kbenoit** [comment]
This is for the workaround to implement #521? It works like `phrase()`:

```r
> as.tokens(kwic(toks, phrase("b c"), join = FALSE))
tokens from 1 document.
text1.1 :
[1] "a" "b" "c" "d"

> as.tokens(kwic(toks, c("b", "c"), join = TRUE))
tokens from 1 document.
text1.1 :
[1] "a" "b" "c" "d"
```

but if we keep the `join` argument for now, it's unlikely to cause trouble if we remove it, since neither I nor @mpadge could figure out what it did from either the description or the behaviour...

**Comment by koheiw** [comment]
We did not make any progress regarding #521... This is the crazy workaround to implement that function with `kwic`. I am sure that no user of Wordsmith will figure this out: 
```r
toks <- tokens(data_corpus_inaugural)
toks_kw <- as.tokens(kwic(toks, c('econom*', 'financ*'))
toks_kw <- tokens_remove(toks_kw, c('econom*', 'financ*'))

mx_kw <-dfm(toks_kw)
mx <- dfm(toks)

col <- textstat_keyness(rbind(mx_kw, mx), c(rep(TRUE, ndoc(mx_kw)), rep(FALSE, ndoc(mx))))

head(col, 20)

# chi2            p n_target n_reference
# expenditures 85.55577 0.000000e+00        5          24
# rigid        79.52689 0.000000e+00        3           7
# simplicity   73.04510 0.000000e+00        2           2
# social       61.42797 4.551914e-15        5          34
# frugality    57.84546 2.831069e-14        2           3
# intricate    57.84546 2.831069e-14        2           3
# recovery     55.41849 9.736656e-14        3          11
# expenditure  44.79168 2.191525e-11        3          14
# strict       39.57542 3.156306e-10        3          16
# (            35.35559 2.746792e-09        3          18
# )            35.35559 2.746792e-09        3          18
# modern       35.35559 2.746792e-09        3          18
# strongest    27.46865 1.596617e-07        2           8
# idealism     27.46865 1.596617e-07        2           8
# world's      26.46035 2.690036e-07        3          24
# basis        26.46035 2.690036e-07        3          24
# sound        20.81606 5.055724e-06        3          30
# expansion    20.47245 6.049588e-06        2          11
# public       19.43352 1.041627e-05        8         224
# industrial   19.36809 1.077932e-05        3          32
```

**Comment by mpadge** [comment]
How about this: Restore it to default `join = TRUE` with same behaviour as now, and have `join = FALSE` split the keywords. Example of current behaviour:
```
> kwic(data_corpus_inaugural, c ("disagreements", "honestly"), window = 2)
  [1805-Jefferson, 1990:1990]    be directed |        honestly        | to the           
     [1817-Monroe, 2916:2916]       has been |        honestly        | made.
     [1837-VanBuren, 363:363] public servant |        honestly        | laboring their
     [1853-Pierce, 1609:1609]     firmly and |        honestly        | carried out
    [1885-Cleveland, 348:348] cheerfully and |        honestly        | abandon all      
  [1885-Cleveland, 1375:1375]     fairly and |        honestly        | treated as       
  [1893-Cleveland, 1361:1361]        them to |        honestly        | and considerately
      [1933-Roosevelt, 58:58]    shrink from |        honestly        | facing conditions
 [1953-Eisenhower, 1735:1735]  logically and |        honestly        | toward secure    
      [2017-Trump, 1212:1213]     debate our | disagreements honestly | , but            
```
Example of what `join = FALSE` could offer without mucking up other `kwic` functionality:
```
> kwic(data_corpus_inaugural, c ("disagreements", "honestly"), window = 2)
  [1805-Jefferson, 1990:1990]       be directed |    honestly   | to the           
     [1817-Monroe, 2916:2916]          has been |    honestly   | made.
     [1837-VanBuren, 363:363]    public servant |    honestly   | laboring their
     [1853-Pierce, 1609:1609]        firmly and |    honestly   |  carried out
    [1885-Cleveland, 348:348]    cheerfully and |    honestly   | abandon all      
  [1885-Cleveland, 1375:1375]        fairly and |    honestly   | treated as       
  [1893-Cleveland, 1361:1361]           them to |    honestly   | and considerately
      [1933-Roosevelt, 58:58]       shrink from |    honestly   | facing conditions
 [1953-Eisenhower, 1735:1735]     logically and |    honestly   | toward secure    
      [2017-Trump, 1212:1212]        debate our | disagreements | honestly,            
      [2017-Trump, 1213:1213] our disagreements |    honestly   | , but            
```
so `join = FALSE` would directly give positions of every single part of `pattern`. (And Donny would double his coverage - love that "honestly, but ...", and the fact that the Don is - regex notwithstanding - the only pres to have mentioned honest disagreements) In short: I want those two keywords to be treated as two keywords each able to be analysed in its own right, and not mashed together just because of accidental co-location.

-----------

I tried to have a go at implementing this, but couldn't figure out the logic behind [`regex2id`](https://github.com/kbenoit/quanteda/blob/master/R/regex2fixed.R), which brings me to a separate issue that I'll save you the trouble of actually opening (because I'm sure neither of us have the time to do this at present): It would make it much easier for other people to contribute to the code if all functions were documented in consistent `roxygen` format (with the magic `@noRd`). I really tried to figure out why `regex2id` returned the kind of object it did, but that list has no names, and no explanation of why it's structured that way. That's not a criticism at all - just a note for future reference. I'm really appreciative of your engagement with my issues here!

**Comment by koheiw** [comment]
These looks like the same as current behavior. Please also see my comment on #912. Do you have any thoughts on #521?

I agree that I should use the `@noRd` magic to document internal function. It is very important to make this repository a welcoming place to new contributors!

**Comment by mpadge** [comment]
Oh yeah, sorry, I was using `0.9.9.89`, and neglected to check behaviour in current `0.9.9.90`. You're right, that is exactly what it currently does. Consider this then just a plea to leave the default behaviour (`join = FALSE`) as is. But I guess that `join = TRUE` would also be very useful in many contexts?

@koheiw Your #521 looks interesting, and may be another argument for improving the efficiency of `kwic()` - along with the example of @kbenoit in #912 which is extremely s l o w . . .
```
kwic(data_corpus_inaugural, phrase("poverty from * ?ffect* of war"))
```
If `kwic` were more efficient, you'd probably be able to do your collocation analysis using the scheme suggested at the end of that issue. I imagine much of the inefficiency arises in `regex2id`, but hard to tell because of the aforementioned comment. Suffice to say that in the text I ran to examine the `regex2id` output, it was a highly redundant object. I didn't quantify it, but it seemed like definitely more than half of the values contained were redundant. Improvement must be possible there - I just don't understand the structure of it enough to suggest what.

**Comment by kbenoit** [comment]
OK now that I see the point of `join` (once again!) I agree, let's leave `kwic()` as is, with `join` but with it set by default to `FALSE`.

@mpadge we've opened an issue to add the documentation you've requested. I completely agree that it's needed, especially if that helps contributions, which are welcomed! We'd welcome generalizing the search capabilities and in improving performance.

On #521 I know how this can be done with existing tools, and we can work on this after the CRAN refresh.
