### ISSUE TITLE
Improve look and content of quanteda.io

### ISSUE THREAD

**Issue by koheiw** [kbenoit/quanteda#938]
http://quanteda.io, especially its to page, does not look good. We have fairly good documentation in the package, but potential users only see the website to assess the quality of the package. We have the same amount of informaton as https://radimrehurek.com/gensim/, but that website looks so much better. At least, we should not use **README** for Github as a top page.

**Comment by kbenoit** [comment]
I agree. We can improve this substantially, either by tweaking the configuration of **pkgdown** that it's built on, or by setting up an overall page in **blogdown** as per e.g. https://github.com/tidyverse/tidyverse.org, which links to individual package sites built in **pkgdown** such as http://dplyr.tidyverse.org.

**Comment by koheiw** [comment]
OK, let's do it. I found three themes that we can use with **blogdown**:
https://themes.gohugo.io/hugo-theme-learn/
https://themes.gohugo.io/hugo-alabaster-theme/
https://themes.gohugo.io/hugo-universal-theme/
I like the first one the best, because we do not need to create a visual ourselves (like the last one), but still a lot of colors in its elements. The second one is a bit boring, but works.

**Comment by kbenoit** [comment]
The complication is that while **blogdown** is built on Hugo, **pkgdown** is not. Furthermore, **blogdown** recommends caution when using other Hugo themes not already adapted for **blogdown**, since there is some customisation required that may break easily when **blogdown** is updated. (See Yihui's book on blogdown.)

**pkgdown** appears to be basic HTML and CSS, although of course it's very customisable. If we do it the **tidyverse** way, then we would create the landing page (for **quanteda**, but also **readtext** and **spacyr** for instance) in **blogdown**, and then use **pkgdown** for each package's documentation. But there are many ways to customise or theme **pkgdown** to make it look better. (Including not using the README.md for the landing page.)

**Comment by koheiw** [comment]
Choice of website framework depends on the content. I think we need:

- how to start tutorials
   - installation
   - very basic commands
- code gallery (examples of basic and applied usage like http://gallery.rcpp.org/)
- comparison with other packages (R, Python tools, Wordsmith, Wordstat etc.)
   - performance comparison
   - code translation table (from other tools to quanteda) 
- use cases
   - projects using quanteda
   - user testimony
- API documentation

Content for potential users has to be in multiple languages (English, Japanese, Chinese, Spanish etc). I think pages for API documentation should be generated in the preset way using **pkgdown**, but other pages are relatively independent of the package itself, so we can create a repository separately from quanteda.
